header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: OpsMx, Inc

  paths-ignore:
    - 'bin'
    - 'buildtime'
    - '**/*.md'
    - 'LICENSE'
    - 'NOTICE'
    - .gitignore
    - .github
    - .licenserc.yaml
    - '**/*.yaml'
    - go.sum
    - go.mod
    - 'ssdjwtauth/testdata'
    - sample-config.yaml

  comment: on-failure

# If you don't want to check dependencies' license compatibility, remove the following part
dependency:
  files:
    - go.mod